//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalEksamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestyrelseRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BestyrelseRole()
        {
            this.Bestyrelse_Tb = new HashSet<Bestyrelse_Tb>();
        }
    
        public int Id { get; set; }
        public string MedlemRole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestyrelse_Tb> Bestyrelse_Tb { get; set; }
    }
}
