//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalEksamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestyrelse_Tb
    {
        public int Id { get; set; }
        public string MedlemName { get; set; }
        public string MedlemBeskrivelse { get; set; }
        public string Email { get; set; }
        public string MedlemImg { get; set; }
        public int Fk_MedlemRole { get; set; }
    
        public virtual BestyrelseRole BestyrelseRole { get; set; }
    }
}
