//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalEksamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventsTb()
        {
            this.TilmedlingTbs = new HashSet<TilmedlingTb>();
        }
    
        public int Id { get; set; }
        public string EventTitle { get; set; }
        public System.DateTime EventDato { get; set; }
        public System.TimeSpan tid { get; set; }
        public string Rubrik { get; set; }
        public string UnderBrik { get; set; }
        public string Region { get; set; }
        public double Distance { get; set; }
        public Nullable<int> PladserAntal { get; set; }
        public double Pris { get; set; }
        public string EventImg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TilmedlingTb> TilmedlingTbs { get; set; }
    }
}
