//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalEksamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class SponsorerTb
    {
        public int Id { get; set; }
        public string SponName { get; set; }
        public string sponLogo { get; set; }
        public int Fk_Level { get; set; }
    
        public virtual SponsLevelTb SponsLevelTb { get; set; }
    }
}
