//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalEksamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class TilmedlingTb
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public int Fk_EventId { get; set; }
    
        public virtual EventsTb EventsTb { get; set; }
    }
}
